---
- hosts: all
  sudo: yes
  sudo_user: root
  tasks:
    - name: Download latest docker binary archive
      get_url:
        url: "http://get.docker.io/builds/Linux/x86_64/docker-latest.tgz"
        dest: "/tmp"
    - name: Extract docker binary archive
      unarchive:
        src: "/tmp/docker-latest.tgz"
        dest: "/"
        copy: no
    - name: Copy service files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {
          src: "docker.socket",
          dest: "/etc/systemd/system"
        }
        - {
          src: "docker.service",
          dest: "/etc/systemd/system"
        }
    - name: Make sure docker service is enabled and started
      service:
        name: "docker.service"
        enabled: "yes"
        state: "started"
    - name: Remove docker archive
      file:
        path: "/tmp/docker-latest.tgz"
        state: "absent"